<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Rapinator</title>
    <link rel="stylesheet" href="css/accueil.css" type="text/css" />
</head>
<body>
    
    <header>
        <nav>
            <a href="Form/destroy.php" class="deco">Deconnexion</a>
        </nav>
    </header>
    
    
    <main>
    <div>
    <h1>Bienvenu a toi sur Rapinator !!</h1>
    <p>Je suis Rapinator laisse moi deviner ton Rappeur preferer</p>
    <img src="img/Designer2.jpeg">
    <a href ="game.php"><button>Commencer le Jeu</button></a>
</div>
</main>
<footer>
        <p>© Copyright 2025 3WA</p>
    </footer>

</body>
</html>