<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="css/style.css" type="text/css" />
    <title>Rapinator</title>
</head>

<body>
    
    <main>
        
        <div class="connection">
            <h1>Rapinator</h1>
            <div class="connexion">
                <a href="./Form/register.php">Register</a>
                <a href="./Form/signin.php">Login</a>
            </div>
            <img src="img/Designer2.jpeg" alt="Rapinator">
        </div>
        
    </main>
    
    <footer>
        <p>© Copyright 2025 3WA</p>
    </footer>

</body>

</html>
