<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Rapinator</title>
</head>

<body>
    
    <header>
        <nav>
            <a href="Form/destroy.php">Deconnexion</a>
        </nav>
    </header>
    
    <main>
        
        <?php include "$template.phtml" ?>
        
    </main>
    <footer>
        <p>© Copyright 2025 3WA</p>
    </footer>
</body>

</html>