<div class="">
    
    <h1>Register</h1>
    <div class="">
        
        <form method="POST">
            
            <label for="name">Name :</label>
            <input type="text" id="name" name="name" required>
            
            <label for="email">Email :</label>
            <input type="text" id="email" name="email" required>
    
            <label for="new-password">Password :</label>
            <input type="password" id="new-password" name="password" required>
    
            <button>Register</button>
        </form>
        
    </div>
</div>
    